### ISSUE TITLE
mqtts

### ISSUE THREAD

**Issue by darxkies** [gomqtt/client#2]
After taking a look at the client and transport code there is no way of passing the information related to TLS/MQTTS such as certificates and so on. IMO, exporting the default dialer in transport (sharedDialer) would solve the problem. If there is another way please let me know.

**Comment by 256dpi** [comment]
Thanks for raising this! Indeed, the current implementation does not support this. I think the best solution would be to add a `Dialer` field to the client config. That way the dialer can be reused among clients. I wouldn't suggest to export the shared dialer as it could interfere with other code. Would that work in your situation?

**Comment by 256dpi** [comment]
I already went ahead and implemented it this way. The new release is tagged as `v0.4.2`.

**Comment by darxkies** [comment]
That is perfect. Thank you.
